[package]
name = "mahjong_game"
version = "0.1.0"
edition = "2024"

[dependencies]
mahjong_lib = { path = "../lib" }

iced = { version = "0.14.0", features = ["debug", "image", "svg"] }
derivative = "2.2.0"
rand = "0.9.2"
strum = "0.27"
strum_macros = "0.27"

[dev-dependencies]
iced_comet = "0.14.0"
