use rand::{rng, seq::SliceRandom};

use mahjong_lib::Tile;

use crate::app::{game::GameTile, settings::GameSettings};

pub fn init_deck(game_settings: &GameSettings) -> Vec<GameTile> {
    let raw_deck = vec![
        Tile::MAN_1,
        Tile::MAN_1,
        Tile::MAN_1,
        Tile::MAN_1,
        Tile::MAN_2,
        Tile::MAN_2,
        Tile::MAN_2,
        Tile::MAN_2,
        Tile::MAN_3,
        Tile::MAN_3,
        Tile::MAN_3,
        Tile::MAN_3,
        Tile::MAN_4,
        Tile::MAN_4,
        Tile::MAN_4,
        Tile::MAN_4,
        Tile::MAN_5,
        Tile::MAN_5,
        Tile::MAN_5,
        Tile::MAN_5,
        Tile::MAN_6,
        Tile::MAN_6,
        Tile::MAN_6,
        Tile::MAN_6,
        Tile::MAN_7,
        Tile::MAN_7,
        Tile::MAN_7,
        Tile::MAN_7,
        Tile::MAN_8,
        Tile::MAN_8,
        Tile::MAN_8,
        Tile::MAN_8,
        Tile::MAN_9,
        Tile::MAN_9,
        Tile::MAN_9,
        Tile::MAN_9,
        Tile::TONG_1,
        Tile::TONG_1,
        Tile::TONG_1,
        Tile::TONG_1,
        Tile::TONG_2,
        Tile::TONG_2,
        Tile::TONG_2,
        Tile::TONG_2,
        Tile::TONG_3,
        Tile::TONG_3,
        Tile::TONG_3,
        Tile::TONG_3,
        Tile::TONG_4,
        Tile::TONG_4,
        Tile::TONG_4,
        Tile::TONG_4,
        Tile::TONG_5,
        Tile::TONG_5,
        Tile::TONG_5,
        Tile::TONG_5,
        Tile::TONG_6,
        Tile::TONG_6,
        Tile::TONG_6,
        Tile::TONG_6,
        Tile::TONG_7,
        Tile::TONG_7,
        Tile::TONG_7,
        Tile::TONG_7,
        Tile::TONG_8,
        Tile::TONG_8,
        Tile::TONG_8,
        Tile::TONG_8,
        Tile::TONG_9,
        Tile::TONG_9,
        Tile::TONG_9,
        Tile::TONG_9,
        Tile::BAMBOO_1,
        Tile::BAMBOO_1,
        Tile::BAMBOO_1,
        Tile::BAMBOO_1,
        Tile::BAMBOO_2,
        Tile::BAMBOO_2,
        Tile::BAMBOO_2,
        Tile::BAMBOO_2,
        Tile::BAMBOO_3,
        Tile::BAMBOO_3,
        Tile::BAMBOO_3,
        Tile::BAMBOO_3,
        Tile::BAMBOO_4,
        Tile::BAMBOO_4,
        Tile::BAMBOO_4,
        Tile::BAMBOO_4,
        Tile::BAMBOO_5,
        Tile::BAMBOO_5,
        Tile::BAMBOO_5,
        Tile::BAMBOO_5,
        Tile::BAMBOO_6,
        Tile::BAMBOO_6,
        Tile::BAMBOO_6,
        Tile::BAMBOO_6,
        Tile::BAMBOO_7,
        Tile::BAMBOO_7,
        Tile::BAMBOO_7,
        Tile::BAMBOO_7,
        Tile::BAMBOO_8,
        Tile::BAMBOO_8,
        Tile::BAMBOO_8,
        Tile::BAMBOO_8,
        Tile::BAMBOO_9,
        Tile::BAMBOO_9,
        Tile::BAMBOO_9,
        Tile::BAMBOO_9,
        Tile::EAST_WIND,
        Tile::EAST_WIND,
        Tile::EAST_WIND,
        Tile::EAST_WIND,
        Tile::SOUTH_WIND,
        Tile::SOUTH_WIND,
        Tile::SOUTH_WIND,
        Tile::SOUTH_WIND,
        Tile::WEST_WIND,
        Tile::WEST_WIND,
        Tile::WEST_WIND,
        Tile::WEST_WIND,
        Tile::NORTH_WIND,
        Tile::NORTH_WIND,
        Tile::NORTH_WIND,
        Tile::NORTH_WIND,
        Tile::WHITE_DRAGON,
        Tile::WHITE_DRAGON,
        Tile::WHITE_DRAGON,
        Tile::WHITE_DRAGON,
        Tile::GREEN_DRAGON,
        Tile::GREEN_DRAGON,
        Tile::GREEN_DRAGON,
        Tile::GREEN_DRAGON,
        Tile::RED_DRAGON,
        Tile::RED_DRAGON,
        Tile::RED_DRAGON,
        Tile::RED_DRAGON,
    ];
    let mut deck: Vec<GameTile> = raw_deck.into_iter().map(GameTile::from).collect();

    if game_settings.has_flowers {
        deck.push(GameTile::from(Tile::PLUM_FLOWER));
        deck.push(GameTile::from(Tile::ORCHID_FLOWER));
        deck.push(GameTile::from(Tile::CHRYSANTHEMUM_FLOWER));
        deck.push(GameTile::from(Tile::BAMBOO_FLOWER));
    }
    if game_settings.has_seasons {
        deck.push(GameTile::from(Tile::SPRING_SEASON));
        deck.push(GameTile::from(Tile::SUMMER_SEASON));
        deck.push(GameTile::from(Tile::AUTUMN_SEASON));
        deck.push(GameTile::from(Tile::WINTER_SEASON));
    }
    if game_settings.has_joker {
        deck.push(GameTile::from(Tile::JOKER));
    }

    let mut rng = rng();
    deck.shuffle(&mut rng);
    deck
}
